### ISSUE TITLE
Not all errors are highlighted when used with Markdown Editing plugin

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#10]
### Summary

Not all errors are highlighted when used with Markdown Editing plugin. This plugin has been downloaded more than 200,000 times, it is included in the Top 100 of plugins, so I think it is necessary to consider its use.
### Expected behavior

Highlighting all errors as other syntaxes.

![PlainText syntax](http://i.imgur.com/wnIjbSU.png)

In code fragments I also saw typos:

![Typos in code](http://i.imgur.com/2lKGDxG.png)
### Actual behavior

Highlighting only current error.

![MarkdownEditing](http://i.imgur.com/vHf1LFi.png)
### Steps to reproduce

I installed a clean Sublime Text without plugins [MarkdownEditing](https://packagecontrol.io/packages/MarkdownEditing) and LanguageTool. I open file with `.md` extension. `Ctrl+Shift+P` → `Language Tool: Check Text`.  I chose different syntaxes: `Markdown`, `Markdown GFM` and `MultiMarkdown` — problem still exists.
### Environment
- Operating system and version:
  - [√] Windows 10 Education
- Sublime Text:
  - Build 3114

**Comment by Kristinita** [comment]
In Markdown GFM syntax is white selection on white background. But how change color of selection? I try to change different parameters in [MarkdownEditor.TmTheme file](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/MarkdownEditor.tmTheme), but I was not able to change the color. Thanks.

**Comment by gtarawneh** [comment]
@Kristinita Can you provide a sample markdown file to reproduce this issue?

**Comment by Kristinita** [comment]
@gtarawneh , <https://gist.github.com/a1deddf4c8a7fb84b7435ef3c5ec0996>. Stack trace after <kbd>Alt+↓</kbd> in line 24. Thanks.

**Comment by gtarawneh** [comment]
@Kristinita Is this an intermittent issue or can you reproduce it reliably? in the latter case can you list the exact steps to reproduce (including the full stack trace please)? I've installed MarkdownEditing and ran a Language check on the file `https://gist.github.com/a1deddf4c8a7fb84b7435ef3c5ec0996`  but I was able to navigate between language problems without any issue.

Thanks for your patience.

**Comment by Kristinita** [comment]
@gtarawneh, I'm sorry, when I wrote my previous comment, I think, what I wrote comment to issue #12. Previous my comment for issue #12.

Problem in this issue I reproduce on new Sublime Text without plugins and user settings. Steps to reproduce:

1. Install MarkdownEditing plugin.
2. Open any markdown file.
3. <kbd>Ctrl+Shift+P</kbd> → `SetSyntax: Markdown GFM`.
4. Run LanguageTool in opened markdown file.

Thanks.

**Comment by Kristinita** [comment]
@gtarawneh , any ideas?

**Comment by gtarawneh** [comment]
@Kristinita Sorry I've had trouble reproducing this issue so had to push it down the queue. I'll get on it as soon as I get some free time.

**Comment by lf-araujo** [comment]
@gtarawneh I can reproduce it in my machine. I am running subl3 in Manjaro.

**Comment by Kristinita** [comment]
@facelessuser, сфо you give the cue, how we can fix these problem? For example, for your package RegReplace results for Markdown GFM syntax are highlight black color:

![**Reg Replace**](http://i.imgur.com/nQi2go5.png)

Selection color not = background color. It's good.

Thanks.

**Comment by facelessuser** [comment]
So, let me get this straight.  You are unhappy with the color this plugin highlights with?

If that is true, the author could make the scope they use to highlight configurable.  Plugin highlight regions are added by specifying a scope to use to get the color.  If that scope is similar to the background color, you will get faint highlights.  I took a quick look, and I think this plugin uses the String scope to highlight regions.  Does this sound right?  I usually expose these kind of things in my settings file when writing plugins.  Just because it is a good color on my theme does not mean it will be a good color on all themes.

Hopefully that helps and I interpreted the issue correctly.

**Comment by Kristinita** [comment]
@gtarawneh ?

**Comment by gtarawneh** [comment]
Alright, I added a `highlight-scope` setting to enable users to customize the outline color for detected problem. I've set the default to `comment` because it seems to work well across different themes, including Markdown GFM but the setting can be changed to `comment`, `constant` or any of the region types listed in:

https://www.sublimetext.com/docs/3/scope_naming.html
