### ISSUE TITLE
[Feature request] Quick run own server

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#17]
### Request

It would be nice if there was a quick start Language Tool, if user use own LanguageTool server.

### Justification

Now I need many steps, to start working with LanguageTool in Sublime Text: I open any terminal → I input `java -jar E:/Chocolatey/lib/languagetool/tools/LanguageTool-3.5/languagetool.jar` in terminal → I close terminal → I minimized LanguageTool to tray → <kbd>Ctrl+Shift+P</kbd> → `LanguageTool: CheckText`. It takes me a long time.

### Extended behavior

<kbd>Ctrl+Shift+P</kbd> → `LanguageTool: Run Own Server And Check Text` → follow all the action, which I described in the previous paragraph. In settings will be added parameter `languagetool_path`.

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita I added a command (`LanguageTool: Start Local Server`) to start a local LT server in the background through Sublime Text. I didn't bundle this with the check text command because that would require the plugin to manage the launched process (i.e. check if its opened etc.) which, even if possible, would be difficult/problematic to implement.

To get this working you only need to modify the `languagetool_jar` setting to point to your local LT jar (e.g. `E:/Chocolatey/lib/languagetool/tools/LanguageTool-3.5/languagetool.jar`). Enjoy!
